# You need to provide the contents for client-secret, email, clientID, subscriptionID, tenantID,
# resourceGroupName (for the DNS zone) and hostedZoneName (domain name).
apiVersion: v1
kind: Secret
metadata:
  name: azure-dns-secret
  namespace: ingress-basic
type: Opaque
data:
  client-secret: /* Base64 */
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: ingress-basic
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${ACME_EMAIL}
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        azureDNS:
          clientID: ${CLIENT_ID}
          clientSecretSecretRef:
            name: azure-dns-secret
            key: client-secret
          subscriptionID: /* "xxxx-xxx-xxx-xxx-xxxx" */
          tenantID: /* "xxxx-xxx-xxx-xxx-xxxx" */
          resourceGroupName: ${DNS_RG}
          hostedZoneName: ${DOMAIN}
          environment: AzurePublicCloud