apiVersion: v1 
kind: Namespace 
metadata: 
  name: jaeger 
  labels: 
    name: jaeger 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: jaeger
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one
          args:
          - --collector.zipkin.host-port=9411
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 9411
          resources:
            limits:
              cpu: 500m
              memory: 512M
            requests:
              cpu: 100m
              memory: 256M
---
apiVersion: v1
kind: Service
metadata:
  namespace: jaeger
  name: jaeger
spec:  
  ports:
  - port: 80    
    targetPort: 16686
  selector:
    app: jaeger  
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger-ingress
  namespace: jaeger
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    # Change to the domain you have configured
    - jaeger.contoso.com
    secretName: tls-secret
  rules:
  # Change to the domain you have configured
  - host: jaeger.contoso.com
    http:
      paths:      
      - backend:
          service: 
            name: jaeger
            port: 
              number: 16686
        path: /
        pathType: Prefix